CREATE SCHEMA IF NOT EXISTS HO06 DEFAULT CHARACTER SET utf8;

USE HO06;

-- ---------------------
-- Table HO06.CURSO
-- ---------------------
CREATE TABLE IF NOT EXISTS HO06.CURSO(
	SIGLA VARCHAR(5) PRIMARY KEY NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    HORAS TINYINT(3) UNSIGNED,
    CUSTO FLOAT UNSIGNED,
    AREA VARCHAR(5) NOT NULL,
    FOREIGN KEY (AREA) REFERENCES AREA (SIGLA)
);

-- ---------------------
-- Table HO06.AREA
-- ---------------------
CREATE TABLE IF NOT EXISTS HO06.AREA(
	SIGLA VARCHAR(5) PRIMARY KEY NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    SUPER_AREA VARCHAR(5) NOT NULL,
    FOREIGN KEY (SUPER_AREA) REFERENCES AREA (SIGLA)
);

-- ---------------------
-- Table HO06.MODULO
-- ---------------------
CREATE TABLE IF NOT EXISTS HO06.MODULO(
	SIGLA VARCHAR(5) PRIMARY KEY NOT NULL,
	NOME VARCHAR(45) NOT NULL,
    CURSO VARCHAR(5) NOT NULL,
    FOREIGN KEY (CURSO) REFERENCES CURSO (SIGLA)
);

-- ---------------------
-- Table HO06.TOPICO
-- ---------------------
CREATE TABLE IF NOT EXISTS HO06.TOPICO(
	MODULO VARCHAR(5) NOT NULL,
	SIGLA VARCHAR(5) NOT NULL,
    PRIMARY KEY (MODULO, SIGLA),
	NOME VARCHAR(45) NOT NULL,
    HORAS TINYINT(3) UNSIGNED,
    FOREIGN KEY (MODULO) REFERENCES MODULO (SIGLA)
);

CREATE TABLE IF NOT EXISTS HO06.ALUNO(
	CPF CHAR(11) PRIMARY KEY NOT NULL,
    NOME VARCHAR(25) NOT NULL,
    SOBRENOME VARCHAR(55) NOT NULL,
    SEXO CHAR(1),
    DATA_NASCIMENTO DATE
);

-- ---------------------
-- Table HO06.PROFESSOR
-- ---------------------
CREATE TABLE IF NOT EXISTS HO06.PROFESSOR(
	CURSO VARCHAR(5) PRIMARY KEY NOT NULL,
	CPF CHAR(11) PRIMARY KEY NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    FOREIGN KEY (CURSO) REFERENCES CURSO (SIGLA)
);

-- ---------------------
-- Table HO06.MATRICULA
-- ---------------------
CREATE TABLE IF NOT EXISTS HO06.MATRICULA(
	CURSO VARCHAR(5) PRIMARY KEY NOT NULL,
    ALUNO CHAR(11) PRIMARY KEY NOT NULL,
    `DATA` DATE,
    PAGO BOOLEAN,
    FOREIGN KEY (CURSO) REFERENCES CURSO (SIGLA),
    FOREIGN KEY (ALUNO) REFERENCES ALUNO (CPF)
);